name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main # Adjust based on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 192.241.128.117 >> ~/.ssh/known_hosts

      - name: Deploy to DigitalOcean
        run: |
          ssh root@192.241.128.117 "cd /root/Thermotrap-API && git pull origin main && npm install && npx prisma migrate deploy && npx prisma generate && pm2 restart thermotrap --update-env"
